import Link from "next/link"
import { UserButton } from "@clerk/nextjs/app-beta"
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function UserLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main>
      <nav className="flex gap-8 p-8">
        <Link href={"/user/restaurant"}>Restaurant</Link>
        <Link href={"/user/products"}>Products</Link>
        <Link href={"/user/orders"}>Orders</Link>
        <Link href={"/user/tables"}>Tables</Link>

        <UserButton
          afterSignOutUrl="/"
          appearance={{
            layout: {
              logoPlacement: "none",
            },
            elements: {
              rootBox: "ml-auto",
              userButtonAvatarBox: "h-8 w-8 sm:h-12 sm:w-12",
            },
          }}
        />
      </nav>
      <div className="min-h-full">
        <div className="py-10">
          <div className="mx-auto max-w-7xl sm:px-6 lg:px-8">{children}</div>
        </div>
      </div>
    </main>
  )
}
