import "@/app/globals.css"
import { ClerkProvider } from "@clerk/nextjs/app-beta"
import { dark } from "@clerk/themes"
import { LayoutHelper } from "../_components/layout-helper"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ClerkProvider appearance={{ baseTheme: dark }}>
        <body>
          {/* @ts-ignore  server component             */}
          <LayoutHelper>{children}</LayoutHelper>
        </body>
      </ClerkProvider>
    </html>
  )
}
