import "@/app/globals.css"
import { ClerkProvider } from "@clerk/nextjs/app-beta"
import { dark } from "@clerk/themes"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <ClerkProvider appearance={{ baseTheme: dark }}>
        <body className="h-full">{children}</body>
      </ClerkProvider>
    </html>
  )
}
